from utils import timeIt
'''
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

   Triangle                Tn=n(n+1)/2             1, 3, 6, 10, 15, ...
   Pentagonal              Pn=((n*(3*n-1))/2)      1, 5, 12, 22, 35, ...
   Hexagonal               Hn=(n*(2*n-1))          1, 6, 15, 28, 45, ...
   It can be verified that T285 = P165 = H143 = 40755.

   Find the next triangle number that is also pentagonal and hexagonal.

'''
@timeIt
def problem45():
    triangles = set()
    pentagonals = set()
    hexagonals = set()
    for n in xrange(1,100001):
        triangles.add((n*(n+1))/2)
        pentagonals.add(((n*(3*n-1))/2))
        hexagonals.add((n*(2*n-1)))
    print max(triangles.intersection(pentagonals).intersection(hexagonals))

problem45()
